// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDcH00_vNnPMTVxIeMah78qpJrf2IsLK4',
    appId: '1:288356545823:web:50e8e03421e99ee672ac2a',
    messagingSenderId: '288356545823',
    projectId: 'voting-app-2b333',
    authDomain: 'voting-app-2b333.firebaseapp.com',
    storageBucket: 'voting-app-2b333.appspot.com',
    measurementId: 'G-DZ8YKHQT6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXCw5FB1df_ijMHMtOBgFonB1TMvpyw40',
    appId: '1:288356545823:android:d7383c9981d4232472ac2a',
    messagingSenderId: '288356545823',
    projectId: 'voting-app-2b333',
    storageBucket: 'voting-app-2b333.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nyR2POHcLO6ErD1sH2-exNQnOSJjTIE',
    appId: '1:288356545823:ios:767f41b3edc1c13972ac2a',
    messagingSenderId: '288356545823',
    projectId: 'voting-app-2b333',
    storageBucket: 'voting-app-2b333.appspot.com',
    iosBundleId: 'com.example.votingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0nyR2POHcLO6ErD1sH2-exNQnOSJjTIE',
    appId: '1:288356545823:ios:767f41b3edc1c13972ac2a',
    messagingSenderId: '288356545823',
    projectId: 'voting-app-2b333',
    storageBucket: 'voting-app-2b333.appspot.com',
    iosBundleId: 'com.example.votingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDcH00_vNnPMTVxIeMah78qpJrf2IsLK4',
    appId: '1:288356545823:web:118dd3da70bdb1f572ac2a',
    messagingSenderId: '288356545823',
    projectId: 'voting-app-2b333',
    authDomain: 'voting-app-2b333.firebaseapp.com',
    storageBucket: 'voting-app-2b333.appspot.com',
    measurementId: 'G-R4Y06X2DVL',
  );
}
